import React, { useState, useEffect, useRef } from 'react';
import {
  View,
  StyleSheet,
  FlatList,
  TouchableOpacity,
  Alert,
  Share,
} from 'react-native';
import { router } from 'expo-router';
import Swipeable from 'react-native-gesture-handler/Swipeable';
import { useFridgeStore } from '@/store/fridgeStore';
import { useRecipeStore } from '@/store/recipeStore';
import { FridgeItem, FridgeRecommendations } from '@/types/fridge.types';
import { useGenerateRecipe } from '@/hooks/useGenerateRecipe';
import { LoadingSpinner } from '@/components/ui/LoadingSpinner';
import { Card } from '@/components/ui/Card';
import { LLMService } from '@/services/LLMService';
import { SuggestionsSheet, SuggestionsSheetRef } from '@/components/features/SuggestionsSheet';
import { COLORS, SPACING, LAYOUT, BORDER_RADIUS } from '@/constants/theme';
import { Screen } from '@/components/ui/Screen';
import { H1, H2, Body, Caption } from '@/components/ui/Typography';
import { TextField } from '@/components/ui/TextField';
import { Button } from '@/components/ui/Button';
import { EmptyState } from '@/components/ui/EmptyState';
import { ListRow } from '@/components/ui/ListRow';

export default function FridgeScreen() {
  const { items, isLoading, loadItems, removeItem, clearAll } = useFridgeStore();
  const [searchQuery, setSearchQuery] = useState('');
  const [recommendations, setRecommendations] = useState<FridgeRecommendations | null>(null);
  const [loadingRecommendations, setLoadingRecommendations] = useState(false);
  const [generatingRecipe, setGeneratingRecipe] = useState<string | null>(null);
  const sheetRef = useRef<SuggestionsSheetRef>(null);

  useEffect(() => {
    loadItems();
  }, []);

  // Present the bottom sheet when recommendations become available
  useEffect(() => {
    if (recommendations) {
      console.log('[AI] Presenting SuggestionsSheet. items:', recommendations.recommendations.length, 'recipes:', recommendations.possibleRecipes?.length ?? 0);
      sheetRef.current?.present();
    }
  }, [recommendations]);

  const handleGetRecommendations = async () => {
    if (items.length === 0) {
      Alert.alert('Empty Fridge', 'Add some ingredients first to get recommendations!');
      return;
    }

    setLoadingRecommendations(true);
    try {
      const llmService = new LLMService();
      const ingredientNames = items.map(item => item.name);
      console.log('[AI] Fetching recommendations for:', ingredientNames);
      const result = await llmService.getIngredientRecommendations(ingredientNames);
      console.log('[AI] Recommendations received. items:', result.recommendations.length, 'recipes:', result.possibleRecipes?.length ?? 0);
      setRecommendations(result);
    } catch (error) {
      Alert.alert('Error', 'Failed to get recommendations. Please try again.');
      console.error('Recommendations error:', error);
    } finally {
      setLoadingRecommendations(false);
    }
  };

  const handleShareShoppingList = async () => {
    if (!recommendations) return;

    let message = 'Shopping List\n\n';
    
    recommendations.recommendations.forEach(rec => {
      message += `\u2022 ${rec.ingredient}\n`;
    });

    message += `\nGenerated by StockedFridge`;

    try {
      await Share.share({
        message,
        title: 'Shopping List',
      });
    } catch (error) {
      console.error('Share error:', error);
    }
  };

  const handleSelectRecipe = async (recipeName: string) => {
    if (generatingRecipe) {
      console.log('[AI] Recipe generation already in progress, ignoring tap');
      return;
    }

    console.log('[AI] Recipe selected:', recipeName);
    
    // Generate a full recipe from the fridge items + recipe name
    setGeneratingRecipe(recipeName);
    try {
      const llmService = new LLMService();
      const ingredientNames = items.map(item => item.name);
      
      console.log('[AI] Generating full recipe for:', recipeName, 'with ingredients:', ingredientNames);
      const recipe = await llmService.generateRecipeFromName(recipeName, ingredientNames);
      
      // Save to recipe store
      const { addRecipe } = useRecipeStore.getState();
      await addRecipe(recipe);
      
      // Navigate to recipe detail using the generated recipe ID
      router.push(`/recipe/${recipe.id}` as any);
    } catch (error) {
      console.error('[AI] Recipe generation error:', error);
      Alert.alert('Error', 'Failed to generate recipe. Please try again.');
    } finally {
      setGeneratingRecipe(null);
    }
  };

  const filteredItems = searchQuery
    ? items.filter(item =>
        item.name.toLowerCase().includes(searchQuery.toLowerCase())
      )
    : items;

  const handleClearAll = () => {
    Alert.alert(
      'Clear Fridge',
      'Remove all items from your fridge?',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Clear All',
          style: 'destructive',
          onPress: () => clearAll(),
        },
      ]
    );
  };

  const renderRightActions = () => (
    <View style={styles.swipeDeleteContainer}>
      <Body style={styles.swipeDeleteText}>Delete</Body>
    </View>
  );

  const renderItem = ({ item }: { item: FridgeItem }) => {
    const subtitle = [
      item.quantity && item.unit && `${item.quantity} ${item.unit}`,
      `Added ${new Date(item.addedAt).toLocaleDateString()}`,
    ].filter(Boolean).join(' • ');

    return (
      <Swipeable
        renderRightActions={renderRightActions}
        onSwipeableOpen={() => {
          removeItem(item.id);
        }}
      >
        <ListRow
          title={item.name}
          subtitle={subtitle}
        />
      </Swipeable>
    );
  };

  if (isLoading) {
    return (
      <Screen>
        <LoadingSpinner size="large" />
      </Screen>
    );
  }

  return (
    <Screen>
      {/* Header */}
      <View style={styles.header}>
        <View style={styles.headerText}>
          <H1>My Fridge</H1>
          <Caption style={styles.subtitle}>Track what you have on hand</Caption>
        </View>
        {items.length > 0 && (
          <TouchableOpacity onPress={handleClearAll}>
            <Caption style={styles.clearButton}>Clear All</Caption>
          </TouchableOpacity>
        )}
      </View>

      {/* Search */}
      <TextField
        placeholder="Search ingredients..."
        value={searchQuery}
        onChangeText={setSearchQuery}
        onClear={() => setSearchQuery('')}
        showClearButton={searchQuery.length > 0}
        containerStyle={styles.searchField}
      />

      {/* AI Suggestions Card */}
      {items.length > 0 && (
        <Card style={styles.aiCard} variant="filled">
          <View style={styles.aiCardContent}>
            <View style={styles.aiCardText}>
              <Body style={styles.aiCardTitle}>AI Shopping Suggestions</Body>
              <Caption>See ingredients you don't have that would unlock more meals</Caption>
            </View>
          </View>
          <Button
            title={loadingRecommendations ? 'Analyzing...' : 'Find Missing Ingredients'}
            onPress={handleGetRecommendations}
            disabled={loadingRecommendations}
            loading={loadingRecommendations}
            variant="primary"
            size="small"
          />
        </Card>
      )}

      {/* Items List or Empty State */}
      {filteredItems.length === 0 ? (
        <EmptyState
          iconName={searchQuery ? 'search' : 'archive'}
          title={searchQuery ? 'No items found' : 'Your fridge is empty'}
          description={
            searchQuery
              ? 'Try a different search term'
              : 'Scan ingredients to add them to your fridge'
          }
        />
      ) : (
        <>
          <Caption style={styles.itemCount}>
            {filteredItems.length} {filteredItems.length === 1 ? 'item' : 'items'}
          </Caption>
          <FlatList
            data={filteredItems}
            renderItem={renderItem}
            keyExtractor={item => item.id}
            contentContainerStyle={styles.listContent}
            showsVerticalScrollIndicator={false}
          />
        </>
      )}

      {/* AI Suggestions Sheet */}
      <SuggestionsSheet
        ref={sheetRef}
        recommendations={recommendations}
        onClose={() => {
          console.log('[AI] Sheet closed. Clearing recommendations.');
          setRecommendations(null);
        }}
        onShare={handleShareShoppingList}
        onSelectRecipe={handleSelectRecipe}        generatingRecipe={generatingRecipe}      />
    </Screen>
  );
}

const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: SPACING.lg,
  },
  headerText: {
    flex: 1,
  },
  subtitle: {
    marginTop: SPACING.xs,
    color: COLORS.textMuted,
  },
  clearButton: {
    color: COLORS.danger,
    fontWeight: '500',
  },
  searchField: {
    marginBottom: SPACING.lg,
  },
  aiCard: {
    marginBottom: SPACING.xxl,
  },
  aiCardContent: {
    marginBottom: SPACING.lg,
  },
  aiCardText: {
    flex: 1,
  },
  aiCardTitle: {
    fontWeight: '600',
    marginBottom: SPACING.xs,
  },
  itemCount: {
    marginBottom: SPACING.md,
    color: COLORS.textMuted,
  },
  listContent: {
    paddingBottom: SPACING.xxl,
  },
  swipeDeleteContainer: {
    backgroundColor: COLORS.danger,
    justifyContent: 'center',
    alignItems: 'flex-end',
    paddingHorizontal: SPACING.xl,
    marginBottom: SPACING.sm,
    borderRadius: BORDER_RADIUS.lg,
  },
  swipeDeleteText: {
    color: COLORS.primaryTextOn,
    fontWeight: '600',
  },
});
