import React, { useState, useEffect } from 'react';
import {
  View,
  StyleSheet,
  FlatList,
  TouchableOpacity,
  Alert,
  Modal,
  ScrollView,
  Share,
  Pressable,
} from 'react-native';
import Swipeable from 'react-native-gesture-handler/Swipeable';
import { useFridgeStore } from '@/store/fridgeStore';
import { FridgeItem, FridgeRecommendations } from '@/types/fridge.types';
import { LoadingSpinner } from '@/components/ui/LoadingSpinner';
import { Card } from '@/components/ui/Card';
import { LLMService } from '@/services/LLMService';
import { COLORS, SPACING, LAYOUT, BORDER_RADIUS } from '@/constants/theme';
import { Screen } from '@/components/ui/Screen';
import { H1, H2, Body, Caption } from '@/components/ui/Typography';
import { TextField } from '@/components/ui/TextField';
import { Button } from '@/components/ui/Button';
import { EmptyState } from '@/components/ui/EmptyState';
import { ListRow } from '@/components/ui/ListRow';

export default function FridgeScreen() {
  const { items, isLoading, loadItems, removeItem, clearAll } = useFridgeStore();
  const [searchQuery, setSearchQuery] = useState('');
  const [showRecommendations, setShowRecommendations] = useState(false);
  const [recommendations, setRecommendations] = useState<FridgeRecommendations | null>(null);
  const [loadingRecommendations, setLoadingRecommendations] = useState(false);

  useEffect(() => {
    loadItems();
  }, []);

  const handleGetRecommendations = async () => {
    if (items.length === 0) {
      Alert.alert('Empty Fridge', 'Add some ingredients first to get recommendations!');
      return;
    }

    setLoadingRecommendations(true);
    try {
      const llmService = new LLMService();
      const ingredientNames = items.map(item => item.name);
      const result = await llmService.getIngredientRecommendations(ingredientNames);
      setRecommendations(result);
      setShowRecommendations(true);
    } catch (error) {
      Alert.alert('Error', 'Failed to get recommendations. Please try again.');
      console.error('Recommendations error:', error);
    } finally {
      setLoadingRecommendations(false);
    }
  };

  const handleShareShoppingList = async () => {
    if (!recommendations) return;

    let message = '🛒 Shopping List\n\n';
    
    recommendations.recommendations.forEach(rec => {
      message += `• ${rec.ingredient}\n`;
    });

    message += `\n📱 Generated by StockedFridge`;

    try {
      await Share.share({
        message,
        title: 'Shopping List',
      });
    } catch (error) {
      console.error('Share error:', error);
    }
  };

  const filteredItems = searchQuery
    ? items.filter(item =>
        item.name.toLowerCase().includes(searchQuery.toLowerCase())
      )
    : items;

  const handleClearAll = () => {
    Alert.alert(
      'Clear Fridge',
      'Remove all items from your fridge?',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Clear All',
          style: 'destructive',
          onPress: () => clearAll(),
        },
      ]
    );
  };

  const renderRightActions = () => (
    <View style={styles.swipeDeleteContainer}>
      <Body style={styles.swipeDeleteText}>Delete</Body>
    </View>
  );

  const renderItem = ({ item }: { item: FridgeItem }) => {
    const subtitle = [
      item.quantity && item.unit && `${item.quantity} ${item.unit}`,
      `Added ${new Date(item.addedAt).toLocaleDateString()}`,
    ].filter(Boolean).join(' • ');

    return (
      <Swipeable
        renderRightActions={renderRightActions}
        onSwipeableOpen={() => {
          removeItem(item.id);
        }}
      >
        <ListRow
          title={item.name}
          subtitle={subtitle}
          leftIcon={<Body>🥬</Body>}
        />
      </Swipeable>
    );
  };

  if (isLoading) {
    return (
      <Screen>
        <LoadingSpinner size="large" />
      </Screen>
    );
  }

  return (
    <Screen>
      {/* Header */}
      <View style={styles.header}>
        <View style={styles.headerText}>
          <H1>My Fridge</H1>
          <Caption style={styles.subtitle}>Track what you have on hand</Caption>
        </View>
        {items.length > 0 && (
          <TouchableOpacity onPress={handleClearAll}>
            <Caption style={styles.clearButton}>Clear All</Caption>
          </TouchableOpacity>
        )}
      </View>

      {/* Search */}
      <TextField
        placeholder="Search ingredients..."
        value={searchQuery}
        onChangeText={setSearchQuery}
        onClear={() => setSearchQuery('')}
        showClearButton={searchQuery.length > 0}
        leftIcon={<Body>🔍</Body>}
        containerStyle={styles.searchField}
      />

      {/* AI Suggestions Card */}
      {items.length > 0 && (
        <Card style={styles.aiCard} variant="filled">
          <View style={styles.aiCardContent}>
            <Body style={styles.aiCardIcon}>✨</Body>
            <View style={styles.aiCardText}>
              <Body style={styles.aiCardTitle}>AI Shopping Suggestions</Body>
              <Caption>Get personalized recommendations</Caption>
            </View>
          </View>
          <Button
            title={loadingRecommendations ? 'Analyzing...' : 'Get Suggestions'}
            onPress={handleGetRecommendations}
            disabled={loadingRecommendations}
            loading={loadingRecommendations}
            variant="primary"
            size="small"
          />
        </Card>
      )}

      {/* Items List or Empty State */}
      {filteredItems.length === 0 ? (
        <EmptyState
          icon={searchQuery ? '🔍' : '🥗'}
          title={searchQuery ? 'No items found' : 'Your fridge is empty'}
          message={
            searchQuery
              ? 'Try a different search term'
              : 'Scan ingredients to add them to your fridge'
          }
        />
      ) : (
        <>
          <Caption style={styles.itemCount}>
            {filteredItems.length} {filteredItems.length === 1 ? 'item' : 'items'}
          </Caption>
          <FlatList
            data={filteredItems}
            renderItem={renderItem}
            keyExtractor={item => item.id}
            contentContainerStyle={styles.listContent}
            showsVerticalScrollIndicator={false}
          />
        </>
      )}

      {/* AI Suggestions Modal */}
      <Modal
        visible={showRecommendations}
        animationType="slide"
        transparent={true}
        onRequestClose={() => setShowRecommendations(false)}
      >
        <TouchableOpacity 
          style={styles.modalOverlay}
          activeOpacity={1}
          onPress={() => setShowRecommendations(false)}
        >
          <View style={styles.modalContent}>
            <View style={styles.modalHeader}>
              <H2>AI Suggestions</H2>
              <TouchableOpacity onPress={() => setShowRecommendations(false)}>
                <Body style={styles.modalClose}>✕</Body>
              </TouchableOpacity>
            </View>

            {recommendations && (
              <ScrollView style={styles.modalScroll} showsVerticalScrollIndicator={false}>
                {/* Shopping List */}
                <View style={styles.modalSection}>
                  <Caption style={styles.modalSectionTitle}>🛒 SHOPPING LIST</Caption>
                  <Card variant="filled">
                    {recommendations.recommendations.map((rec, index) => (
                      <View key={index} style={styles.shoppingItem}>
                        <Body>• {rec.ingredient}</Body>
                      </View>
                    ))}
                  </Card>
                </View>

                {/* Possible Recipes */}
                {recommendations.possibleRecipes && recommendations.possibleRecipes.length > 0 && (
                  <View style={styles.modalSection}>
                    <Caption style={styles.modalSectionTitle}>👨‍🍳 RECIPES YOU COULD MAKE</Caption>
                    <Card variant="filled">
                      {recommendations.possibleRecipes.map((recipe, index) => (
                        <View key={index} style={styles.recipeItem}>
                          <Body style={styles.recipeIcon}>🍳</Body>
                          <Body style={styles.recipeText}>{recipe}</Body>
                        </View>
                      ))}
                    </Card>
                  </View>
                )}

                {/* Share Button */}
                <Button
                  title="📤  Share Shopping List"
                  onPress={handleShareShoppingList}
                  variant="primary"
                  fullWidth
                  style={styles.shareButton}
                />
              </ScrollView>
            )}
          </View>
        </TouchableOpacity>
      </Modal>
    </Screen>
  );
}

const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: SPACING.lg,
  },
  headerText: {
    flex: 1,
  },
  subtitle: {
    marginTop: SPACING.xs,
    color: COLORS.textMuted,
  },
  clearButton: {
    color: COLORS.danger,
    fontWeight: '500',
  },
  searchField: {
    marginBottom: SPACING.lg,
  },
  aiCard: {
    marginBottom: SPACING.xxl,
  },
  aiCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SPACING.lg,
  },
  aiCardIcon: {
    fontSize: 32,
    lineHeight: 40,
    marginRight: SPACING.md,
  },
  aiCardText: {
    flex: 1,
  },
  aiCardTitle: {
    fontWeight: '600',
    marginBottom: SPACING.xs,
  },
  itemCount: {
    marginBottom: SPACING.md,
    color: COLORS.textMuted,
  },
  listContent: {
    paddingBottom: SPACING.xxl,
  },
  swipeDeleteContainer: {
    backgroundColor: COLORS.danger,
    justifyContent: 'center',
    alignItems: 'flex-end',
    paddingHorizontal: SPACING.xl,
    marginBottom: SPACING.sm,
    borderRadius: BORDER_RADIUS.lg,
  },
  swipeDeleteText: {
    color: COLORS.primaryTextOn,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: COLORS.bg,
    borderTopLeftRadius: BORDER_RADIUS.xxl,
    borderTopRightRadius: BORDER_RADIUS.xxl,
    width: '100%',
    maxHeight: '85%',
    paddingTop: SPACING.xl,
    paddingHorizontal: LAYOUT.screenPadding,
    paddingBottom: SPACING.xxxl + SPACING.lg,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.xxl,
  },
  modalClose: {
    lineHeight: 28,
    fontSize: 24,
    color: COLORS.textMuted,
  },
  modalScroll: {
    flex: 1,
  },
  modalSection: {
    marginBottom: SPACING.xxl,
  },
  modalSectionTitle: {
    fontWeight: '600',
    letterSpacing: 1,
    marginBottom: SPACING.md,
    color: COLORS.textMuted,
  },
  shoppingItem: {
    paddingVertical: SPACING.sm,
  },
  recipeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: SPACING.sm,
  },
  recipeIcon: {
    marginRight: SPACING.md,
  },
  recipeText: {
    flex: 1,
  },
  shareButton: {
    marginTop: SPACING.lg,
  },
});
